# Site settings
title: "Mitch Smith: Software Engineer and App Developer"
description: "Mitchell (Mitch) Smith is a full time Software Engineer and father from Baltimore Maryland. In his free time he enjoys creating apps as a hobby."
url: "https://mitchell525.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Pages configuration
defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"

# Development settings
livereload: true
incremental: true

# Collections
collections:
  apps:
    output: true
    permalink: /:name/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# SEO settings
twitter:
  username: mitchell525
  card: summary_large_image

# Google Analytics
# OLD - google_analytics: UA-112034969-4
google_analytics: G-JQBKZ4XTC1